openapi: 3.0.0
info:
  version: 0.3.0
  title: Wikimedia EventStreams
  description: Streaming Wikimedia event data over HTTP SSE / EventSource
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  url: https://wikitech.wikimedia.org/wiki/EventStreams

paths:

  /v2/stream/{streams}:
    get:
      x-monitor: false
      tags: [streams]
      summary: Subscribe to one or multiple streams.
      description: >
        Use this route to subscribe to a comma separated list of configured streams.
      parameters:
        - name: streams
          in: path
          description: Comma separated list of stream names to subscribe to.
          schema: { type: array, items: { type: string } }
          required: true
        - name: Last-Event-ID
          in: header
          description: >
            Specifies the Kafka topics, partitions and offsets from which to begin
            streaming. You may not specify topics that are not configured
            to be part of this stream endpoint.
            Example: `[{topic: datacenter1.topic, partition: 0, offset: 12345}, ...]`
          schema:
            type: array
            items:
              type: object
              properties:
                topic:
                  type: string
                partition:
                  type: integer
                offset:
                  type: integer
                timestamp:
                  type: string
        - name: since
          in: query
          description: >
            If given, this timestamp will be used as the historical starting position in
            each the requested streams. since should either be an integer UTC milliseconds
            unix epoch timestamp, or a string timestamp parseable by `Date.parse()`.
            If the timestamp given does not have any corresponding offsets, it will be ignored,
            and the data will begin streaming from the latest position in the stream.
            This parameter is ignored if `Last-Event-ID` is set with offsets (or timestamps)
            for individual topic partition assignments, e.g. when resuming after a disconnect.
            NOTE: Historical timestamp assignment is not supported indefinitely. Depending
            on backend stream configuration, will likely be only one or a few weeks.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
            text/event-stream:
              schema:
                type: string
# NOTE:  Specific /v2/stream/* routes are configured in the routes/stream.js
# dynamically from the stream_config_uri.
